# Site settings
title: Dr Jekyll and Mr. Bava
email: jimgroom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The bava meets Jekyll by way of Github. It's a long story.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jimgroom.me" # the base hostname & protocol for your site
twitter_username: jimgroom
github_username:  jimgroom

# Build settings
markdown: kramdown
