# Site settings
title: bavajekyll
email: jimgroom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 THis is bavajekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jimgroom
github_username:  jimgroom

# Build settings
markdown: kramdown
